server:
    port: 80

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/hcxboot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: soyeajr

swagger:
    enable: true

page:
    defaultPageSize: 10